[package]
name = "ben"
version = "0.1.7"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"
description = "A minimalistic Bencode parser"
license = "MIT"

[dependencies]
itoa = "0.4.5"
bytes = "0.5.4"

